name: clean_starter
description: "An clean architecture starter for Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Support packages
  common_sdk:
    path: packages/common_sdk
  core_sdk:
    path: packages/core_sdk
  core_sdk_impl:
    path: packages/core_sdk_impl
  isar_e2m:
    path: packages/isar_e2m

  # External packages
  auto_size_text:
  connectivity_plus:
  cupertino_icons:
  flutter_bloc:
  flutter_screenutil:
  flutter_svg:
  freezed_annotation:
  gap:
  google_fonts:
  go_router:
  intl:
  logger:
  path_provider:
  permission_handler:
  shared_preferences:
  shimmer_animation:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_gen: ^5.12.0
  flutter_launcher_icons:
  flutter_lints:
  flutter_native_splash:
  freezed:

flutter_gen:
  output: lib/gen/
  line_length: 80
  
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  fullscreen: false
  image: assets/images/empty.png
  android_12:
    color: "#ffffff"
    image: assets/images/empty.png
    fullscreen: false

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter.ttf
          style: normal
