name: json_client
description: "Json Http Client"
version: 0.0.4
homepage:
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  common_sdk:
    path: ../common_sdk
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

