name: isar_e2m
description: "Isar Wrapper"
version: 0.0.4
publish_to: none

isar_version: &isar_version 3.3.0-dev.3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  common_sdk:
    path: ../common_sdk

  isar_community: *isar_version
  isar_community_flutter_libs: *isar_version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  isar_community_generator: *isar_version
